name: "Validate everything"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  QUAY_IO_USERNAME: shepmaster

jobs:
  build_compiler_containers:
    name: "Build ${{ matrix.channel }} compiler container"
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        channel: [stable, beta, nightly]

    env:
      IMAGE_NAME: quay.io/shepmaster/rust-playground-ci-rust-${{ matrix.channel }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: |
            image=moby/buildkit:master

      - name: "Login to Quay"
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ env.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}

      - name: "Build and push 'toolchain' container"
        env:
          TAG_PREFIX: ${{ env.IMAGE_NAME }}:toolchain
        uses: docker/build-push-action@v2
        with:
          context: compiler/base/
          file: compiler/base/Dockerfile
          build-args: |
            channel=${{ matrix.channel }}
          target: toolchain
          pull: true
          push: true
          tags: |
            ${{ env.TAG_PREFIX }}--${{ github.run_id }}
            ${{ env.TAG_PREFIX }}--latest
          cache-from: |
            ${{ env.TAG_PREFIX }}--${{ github.run_id }}
            ${{ env.TAG_PREFIX }}--latest
          cache-to: type=inline
          labels: |
            quay.expires-after=1w

      - name: "Build and push 'bare-sources' container"
        env:
          TAG_PREFIX: ${{ env.IMAGE_NAME }}:bare-sources
        uses: docker/build-push-action@v2
        with:
          context: compiler/base/
          file: compiler/base/Dockerfile
          build-args: |
            channel=${{ matrix.channel }}
          target: bare-sources
          pull: true
          push: true
          tags: |
            ${{ env.TAG_PREFIX }}--${{ github.run_id }}
            ${{ env.TAG_PREFIX }}--latest
          cache-from: |
            ${{ env.TAG_PREFIX }}--${{ github.run_id }}
            ${{ env.TAG_PREFIX }}--latest
          cache-to: type=inline
          labels: |
            quay.expires-after=1w

      - name: "Build and push 'munge' container"
        env:
          TAG_PREFIX: ${{ env.IMAGE_NAME }}:munge
        uses: docker/build-push-action@v2
        with:
          context: compiler/base/
          file: compiler/base/Dockerfile
          build-args: |
            channel=${{ matrix.channel }}
          target: munge
          pull: true
          push: true
          tags: |
            ${{ env.TAG_PREFIX }}--${{ github.run_id }}
            ${{ env.TAG_PREFIX }}--latest
          cache-from: |
            ${{ env.TAG_PREFIX }}--${{ github.run_id }}
            ${{ env.TAG_PREFIX }}--latest
          cache-to: type=inline
          labels: |
            quay.expires-after=1w

      - name: "Build and push 'sources' container"
        env:
          TAG_PREFIX: ${{ env.IMAGE_NAME }}:sources
        uses: docker/build-push-action@v2
        with:
          context: compiler/base/
          file: compiler/base/Dockerfile
          build-args: |
            channel=${{ matrix.channel }}
          target: sources
          pull: true
          push: true
          tags: |
            ${{ env.TAG_PREFIX }}--${{ github.run_id }}
            ${{ env.TAG_PREFIX }}--latest
          cache-from: |
            ${{ env.TAG_PREFIX }}--${{ github.run_id }}
            ${{ env.TAG_PREFIX }}--latest
          cache-to: type=inline
          labels: |
            quay.expires-after=1w

      - name: "Build and push container"
        uses: docker/build-push-action@v2
        with:
          context: compiler/base/
          file: compiler/base/Dockerfile
          build-args: |
            channel=${{ matrix.channel }}
          pull: true
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.run_id }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: |
            ${{ env.IMAGE_NAME }}:${{ github.run_id }}
            ${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
          labels: |
            quay.expires-after=1w

  build_tool_containers:
    name: "Build ${{ matrix.tool }} tool container"
    runs-on: ubuntu-latest
    needs: build_compiler_containers
    continue-on-error: true

    strategy:
      matrix:
        tool: [clippy, miri, rustfmt]
    env:
      IMAGE_NAME: quay.io/shepmaster/rust-playground-ci-tool-${{ matrix.tool }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Login to Quay"
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ env.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}

      - name: "Build and push container"
        uses: docker/build-push-action@v2
        with:
          context: compiler/${{ matrix.tool }}/
          file: compiler/${{ matrix.tool }}/Dockerfile
          build-args: |
            base_image=quay.io/shepmaster/rust-playground-ci-rust-nightly:sources--latest
          pull: true
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.run_id }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: |
            ${{ env.IMAGE_NAME }}:${{ github.run_id }}
            ${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
          labels: |
            quay.expires-after=1w

  build_backend:
    name: "Build backend"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Cache Cargo intermediate products"
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ui/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('ui/**/Cargo.lock') }}-2

      - name: "Build backend"
        run: >-
            mkdir -p ui/target;
            docker
            run
            --rm
            -v $PWD/ui:/ui
            -v ~/.cargo/git:/home/rust/.cargo/git
            -v ~/.cargo/registry:/home/rust/.cargo/registry
            --workdir /ui
            ekidd/rust-musl-builder:stable
            bash -c '
              sudo chown -R rust:rust /home/rust/.cargo /ui/target;
              cargo build --locked --target=x86_64-unknown-linux-musl --release
            '

      - name: "Restore permissions"
        run: >-
          sudo chown -R runner:docker ~/.cargo/ ui/target

      - name: "Save backend artifact"
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: ui/target/x86_64-unknown-linux-musl/release/ui

  build_frontend:
    name: "Build frontend"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Get yarn cache directory path"
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: "Cache yarn intermediate products"
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: "Configure node"
        uses: actions/setup-node@v1
        with:
          node-version: 14.15

      - name: "Install dependencies"
        run: >-
          yarn --cwd ui/frontend/

      - name: "Run tests"
        run: >-
          yarn --cwd ui/frontend/ test

      - name: "Lint"
        run: >-
          yarn --cwd ui/frontend/ test:lint

      - name: "Build frontend"
        run: >-
          yarn --cwd ui/frontend/ run build:production

      - name: "Save frontend artifact"
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: ui/frontend/build

  run_integration_tests:
    name: "Running integration tests"
    runs-on: ubuntu-latest
    needs:
      - build_compiler_containers
      - build_tool_containers
      - build_backend
      - build_frontend

    defaults:
      run:
        working-directory: tests

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Configure Ruby"
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: "Cache bundler intermediate products"
        uses: actions/cache@v2
        with:
          path: tests/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('tests/**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: "Install gems"
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: "Pull containers"
        run: |
          echo quay.io/shepmaster/rust-playground-ci-{rust-{stable,beta,nightly},tool-{clippy,rustfmt,miri}} | xargs -n1 docker pull
          for c in stable beta nightly; do
            docker tag quay.io/shepmaster/rust-playground-ci-rust-$c rust-$c
          done
          for t in clippy miri rustfmt; do
            docker tag quay.io/shepmaster/rust-playground-ci-tool-$t $t
          done

      - name: "Download backend"
        uses: actions/download-artifact@v2
        with:
          name: backend
          path: tests/server/

      - name: "Download frontend"
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: tests/server/built/

      - name: "Run tests"
        env:
          PLAYGROUND_UI_ROOT: server/built/
          PLAYGROUND_CORS_ENABLED: true
          PLAYGROUND_GITHUB_TOKEN: ${{ secrets.PLAYGROUND_GITHUB_TOKEN }}
        run: |
          chmod +x ./server/ui && ./server/ui &
          bundle exec rspec
